using System.Linq;
using System.Text;

namespace Sia.Math.CodeGenerators;

public static class ScopeWriter
{
    public static string RenderTypePartial(TypeShape shape, CodeFragment fragment, bool isPrimary)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var usings = (fragment.Usings ?? []).Distinct().OrderBy(u => u);
        foreach (var u in usings) sb.AppendLine($"using {u};");

        sb.AppendLine();
        sb.AppendLine("#pragma warning disable 0660, 0661, 8981");
        sb.AppendLine();
        sb.AppendLine("namespace Sia.Math;");
        sb.AppendLine();

        var inherits = (fragment.Inherits ?? []).Distinct().OrderBy(i => i).ToArray();

        if (fragment.TypeBody is not null)
        {
            if (isPrimary)
            {
                if (shape.IsVector)
                    sb.AppendLine($"[System.Diagnostics.DebuggerTypeProxy(typeof({shape.TypeName}.DebuggerProxy))]");
                sb.AppendLine("[System.Serializable]");
            }
            sb.Append("public partial struct ").Append(shape.TypeName);
            if (isPrimary && inherits.Length > 0)
                sb.Append(" : ").Append(string.Join(", ", inherits));
            sb.AppendLine();
            sb.AppendLine("{");
            sb.Append(fragment.TypeBody);
            if (!fragment.TypeBody.EndsWith("\n")) sb.AppendLine();
            sb.AppendLine("}");
        }

        if (fragment.MathBody is not null)
        {
            if (fragment.TypeBody is not null) sb.AppendLine();
            sb.AppendLine("public static partial class math");
            sb.AppendLine("{");
            sb.Append(fragment.MathBody);
            if (!fragment.MathBody.EndsWith("\n")) sb.AppendLine();
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    public static string RenderStandaloneFile(string[] headerUsings, string mathBody)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        foreach (var u in headerUsings) sb.AppendLine($"using {u};");
        sb.AppendLine();
        sb.AppendLine("#pragma warning disable 0660, 0661, 8981");
        sb.AppendLine();
        sb.AppendLine("namespace Sia.Math;");
        sb.AppendLine();
        sb.AppendLine("public static partial class math");
        sb.AppendLine("{");
        sb.Append(mathBody);
        sb.AppendLine("}");

        return sb.ToString();
    }
}
