namespace Sia.Math.CodeGenerators;

using System;
using System.Linq;

public static class ScopeWriter
{
    public static string GenerateTypePartial(
        TypeShape shape,
        CodeFragment fragment,
        bool isPrimary)
    {
        var source = CreateFileSource(fragment.Usings ?? []);
        var inherits = (fragment.Inherits ?? [])
            .Distinct()
            .OrderBy(static item => item)
            .ToArray();

        if (fragment.TypeBody is not null) {
            if (isPrimary) {
                if (shape.IsVector) {
                    source.Line(
                        $"[System.Diagnostics.DebuggerTypeProxy(typeof({shape.TypeName}.DebuggerProxy))]");
                }
                source.Line("[System.Serializable]");
            }

            var declaration = $"public partial struct {shape.TypeName}";
            if (isPrimary && inherits.Length > 0) {
                declaration += $" : {string.Join(", ", inherits)}";
            }

            source.Line(declaration);
            source.Line("{");
            WriteBody(source, fragment.TypeBody);
            source.Line("}");
        }

        if (fragment.MathBody is not null) {
            if (fragment.TypeBody is not null) {
                source.Line();
            }

            source.Line("public static partial class math");
            source.Line("{");
            WriteBody(source, fragment.MathBody);
            source.Line("}");
        }

        return source.ToString();
    }

    public static string GenerateStandaloneFile(
        string[] usings,
        string mathBody)
    {
        var source = CreateFileSource(usings);
        source.Line("public static partial class math");
        source.Line("{");
        WriteBody(source, mathBody);
        source.Line("}");
        return source.ToString();
    }

    private static SourceBuilder CreateFileSource(string[] usings)
    {
        var source = new SourceBuilder();
        source.Line("// <auto-generated/>");
        source.Line("#nullable enable");
        source.Line();
        source.Line("namespace Sia.Math;");
        source.Line();

        foreach (var item in usings.Distinct().OrderBy(static item => item)) {
            source.Line($"using {item};");
        }

        if (usings.Length > 0) {
            source.Line();
        }

        source.Line("#pragma warning disable 0660, 0661, 8981");
        source.Line();
        return source;
    }

    private static void WriteBody(SourceBuilder source, string body)
    {
        var lines = body
            .TrimEnd('\r', '\n')
            .Replace("\r\n", "\n")
            .Split('\n');
        var commonIndent = lines
            .Where(static line => !string.IsNullOrWhiteSpace(line))
            .Select(CountLeadingSpaces)
            .DefaultIfEmpty(0)
            .Min();

        source.Indented(content => {
            foreach (var line in lines) {
                content.Line(line.Length >= commonIndent
                    ? line.Substring(commonIndent)
                    : string.Empty);
            }
        });
    }

    private static int CountLeadingSpaces(string line)
    {
        var count = 0;
        while (count < line.Length && line[count] == ' ') {
            count++;
        }
        return count;
    }
}
